Update python-publish.yml to use Trusted Publisher (#74)
Ran into an error with the latest publish attempt:

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading tplink_cloud_api-4.2.0-py3-none-any.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/49.8 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 kB • 00:00 • 130.2 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 kB • 00:00 • 130.2 MB/s
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Username/Password authentication is no longer supported. Migrate to API
         Tokens or Trusted Publishers instead. See                              
         https://pypi.org/help/#apitoken and                                    
         https://pypi.org/help/#trusted-publishers                              
Error: Process completed with exit code 1.
```

Seems that we must now use https://docs.pypi.org/trusted-publishers/

We are loosely following the guidance here https://docs.pypi.org/trusted-publishers/using-a-publisher/ along with advice provided by Gemini